### ISSUE TITLE
AdaptiveAvgPool3d: wait for bug resolved -> delete warning

### ISSUE THREAD

**Issue by schaefertim** [f-dangel/backpack#184]
As soon as https://github.com/pytorch/pytorch/issues/60524 is resolved, we can delete our warnings:
- backpack/core/derivatives/adaptive_avg_pool_nd.py: delete warning in `check_parameters`
- test/core/derivatives/derivatives_test.py: delete test of warning in `test_ea_jac_t_mat_jac_prod` and `test_jac_t_mat_prod`

**Comment by schaefertim** [comment]
I verified that this bug is resolved in torch 1.9.1.

**Comment by f-dangel** [comment]
The bug still persists in `torch==1.9.1`. @schaefertim could you update the [skip condition](https://github.com/tjs111/backpack/blob/b9b11af594e72408428a48b11de96b59ac57f183/test/utils/skip_test.py#L13-L29) in the tests?
